package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type obj = map[string]any

func load(path string) obj {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var o obj
	if json.Unmarshal(b, &o) != nil {
		return nil
	}
	return o
}

func num(o obj, keys ...string) float64 {
	var cur any = o
	for _, k := range keys {
		m, ok := cur.(map[string]any)
		if !ok {
			return 0
		}
		cur = m[k]
	}
	f, _ := cur.(float64)
	return f
}

func f0(v float64) string { return fmt.Sprintf("%.0f", v) }
func f1(v float64) string { return fmt.Sprintf("%.1f", v) }
func f2(v float64) string { return fmt.Sprintf("%.2f", v) }

func thousands(v float64) string {
	s := fmt.Sprintf("%.0f", v)
	n := len(s)
	var b strings.Builder
	for i, c := range s {
		if i > 0 && (n-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(c)
	}
	return b.String()
}

func topCPU(o obj) string {
	m, _ := o["cpu_cores_by_container"].(map[string]any)
	type kv struct {
		k string
		v float64
	}
	var xs []kv
	for k, v := range m {
		f, _ := v.(float64)
		k = strings.TrimSuffix(strings.TrimPrefix(k, "streamforge-"), "-1")
		if strings.HasPrefix(k, "sf-bench-replayer") {
			k = "replayer"
		}
		if strings.HasPrefix(k, "tools-run") {
			continue
		}
		xs = append(xs, kv{k, f})
	}
	sort.Slice(xs, func(i, j int) bool { return xs[i].v > xs[j].v })
	var parts []string
	for i := 0; i < len(xs) && i < 3; i++ {
		parts = append(parts, fmt.Sprintf("%s %.2f", xs[i].k, xs[i].v))
	}
	return strings.Join(parts, ", ")
}

func yes(o obj) string {
	if b, _ := o["sustained"].(bool); b {
		return "yes"
	}
	return "**no**"
}

func writeReport(dir string) error {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	w("# Gate 4: measured results\n\n")
	w("Generated by `bench/gate4.sh` (then `bench report`). Raw JSON for every row is in this directory. ")
	w("Configuration was fixed before measuring and is the same in every run. Sections 1, 2, 4 and 5 come from the first full run. The serving runs (section 3) were repeated after fixing two defects that the first run exposed, and both are reported: the load generator busy-waited and stole a CPU core from the system under test (those first results were discarded), and the cache path suffered a stampede (before/after table below). Hardware: see [`../ENVIRONMENT.md`](../ENVIRONMENT.md); all services share one 2-vCPU host, so these numbers are a floor, not a ceiling.\n\n")

	w("## 1. Ingest throughput (synthetic stream, event time advancing at wall-clock speed)\n\n")
	w("A run is **sustained** if total consumer lag did not grow: the least-squares slope of lag over the window is under 1%% of the offered rate. Freshness = wall time from publishing the event that closes a window to that window's features being committed in the 5-node Raft store (readable linearizably).\n\n")
	w("| Offered ev/s | Window | Published ev/s | Consumed ev/s | Lag slope (ev/s) | Max lag (events) | Sustained | Freshness p50 / p99 (ms) | CPU cores used (top 3) |\n|---|---|---|---|---|---|---|---|---|\n")
	files, _ := filepath.Glob(filepath.Join(dir, "throughput-ingest-*.json"))
	sort.Slice(files, func(i, j int) bool {
		return num(load(files[i]), "offered_rate_eps") < num(load(files[j]), "offered_rate_eps") || (num(load(files[i]), "offered_rate_eps") == num(load(files[j]), "offered_rate_eps") && files[i] < files[j])
	})
	for _, f := range files {
		o := load(f)
		if o == nil {
			continue
		}
		win := f0(num(o, "window_s")) + " s"
		if strings.Contains(f, "final") {
			win = "**" + win + " (final)**"
		}
		w("| %s | %s | %s | %s | %s | %s | %s | %s / %s | %s (total %s) |\n", thousands(num(o, "offered_rate_eps")), win,
			thousands(num(o, "published_rate_eps")), thousands(num(o, "consumed_rate_eps")), f1(num(o, "lag_slope_eps")), f0(num(o, "lag_max")), yes(o),
			f1(num(o, "freshness_p50_ms")), f1(num(o, "freshness_p99_ms")), topCPU(o), f2(num(o, "cpu_cores_total")))
	}
	w("\nWith real-time pacing each zone's windows close once per event-time minute, so the Raft log carries only a few batches per minute regardless of event rate; this table measures the ingest path (Kafka, decoding, windowing). Freshness percentiles here come from few samples (one window close per partition per minute) and are bucket-resolution estimates.\n\n")

	w("## 2. Time-compressed replay of the real TLC month (commit-path stress)\n\n")
	w("Replaying March 2026 at a fixed rate compresses event time: the real stream averages about 1.47 trips/s, so 8,000 ev/s plays one event-time minute every ~11 ms: each partition closes a window roughly every 11 ms (about 90 per second) instead of once a minute, and every closed window produces a row per active zone, in the Raft log and in the Postgres history, so this stresses the commit path. The worker pipelines one proposal per partition and batches whatever closed meanwhile; when commits slow down, batches grow and freshness rises while ingest still keeps up.\n\n")
	w("| Store | Offered ev/s | Event-time speed-up | Sustained | Freshness p50 / p99 (ms) | Raft commit p50 / p99 (ms) | WAL persist p99 (ms) | Proposals/s | Feature rows/s | CPU cores used (top 3) |\n|---|---|---|---|---|---|---|---|---|---|\n")
	files, _ = filepath.Glob(filepath.Join(dir, "throughput-tlc-compressed-*.json"))
	sort.Slice(files, func(i, j int) bool {
		a, b := strings.Contains(files[i], "1node"), strings.Contains(files[j], "1node")
		if a != b {
			return b // 5-node rows first
		}
		return num(load(files[i]), "offered_rate_eps") < num(load(files[j]), "offered_rate_eps")
	})
	for _, f := range files {
		o := load(f)
		if o == nil {
			continue
		}
		store := "5-node Raft"
		if strings.Contains(f, "1node") {
			store = "1 node"
		}
		win := num(o, "window_s")
		w("| %s | %s | %sx | %s | %s / %s | %s / %s | %s | %s | %s | %s |\n", store, thousands(num(o, "offered_rate_eps")), thousands(num(o, "offered_rate_eps")/1.47), yes(o),
			f1(num(o, "freshness_p50_ms")), f1(num(o, "freshness_p99_ms")), f2(num(o, "raft_commit_p50_ms")), f2(num(o, "raft_commit_p99_ms")), f2(num(o, "raft_persist_p99_ms")),
			f0(num(o, "raft_proposals_committed")/win), thousands(num(o, "feature_rows_committed")/win), topCPU(o))
	}

	w("\n## 3. Serving latency (open-loop load, measured from the scheduled send time)\n\n")
	w("`loadgen` sends at a constant rate whether or not earlier requests finished, and measures each request from the time it was *scheduled*, so server stalls are not hidden (no coordinated omission). Deadline 100 ms per request. Max in-flight is the highest number of concurrent outstanding requests observed. The demo replay (TLC at 60x) was ingesting during these runs.\n\n")
	w("| Mode | Entities/request | Rate (req/s) | Requests | Max in-flight | p50 | p90 | p99 | p99.9 | max | Errors | p99 cache hits | p99 leader reads |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	files, _ = filepath.Glob(filepath.Join(dir, "serve-*.json"))
	sort.Slice(files, func(i, j int) bool {
		a, c := load(files[i]), load(files[j])
		if a["mode"] != c["mode"] {
			return fmt.Sprint(a["mode"]) < fmt.Sprint(c["mode"])
		}
		if num(a, "batch") != num(c, "batch") {
			return num(a, "batch") < num(c, "batch")
		}
		return num(a, "rate_rps") < num(c, "rate_rps")
	})
	for _, f := range files {
		o := load(f)
		if o == nil || strings.Contains(f, "1node") {
			continue
		}
		codes, _ := o["codes"].(map[string]any)
		var errs float64
		for k, v := range codes {
			if k != "OK" {
				errs += v.(float64)
			}
		}
		hit, lead := "-", "-"
		if v := num(o, "by_served_from", "SERVED_FROM_CACHE", "p99_ms"); v > 0 {
			hit = f2(v) + " ms (" + thousands(num(o, "by_served_from", "SERVED_FROM_CACHE", "count")) + ")"
		}
		if v := num(o, "by_served_from", "SERVED_FROM_LEADER", "p99_ms"); v > 0 {
			lead = f2(v) + " ms (" + thousands(num(o, "by_served_from", "SERVED_FROM_LEADER", "count")) + ")"
		}
		mode := fmt.Sprint(o["mode"])
		if mode == "bounded" {
			mode = "bounded staleness (cache, TTL 2 s)"
		}
		w("| %s | %s | %s | %s | %s | %s ms | %s ms | **%s ms** | %s ms | %s ms | %s | %s | %s |\n", mode, f0(num(o, "batch")), thousands(num(o, "rate_rps")), thousands(num(o, "requests")), f0(num(o, "max_inflight")),
			f2(num(o, "overall", "p50_ms")), f2(num(o, "overall", "p90_ms")), f2(num(o, "overall", "p99_ms")), f2(num(o, "overall", "p999_ms")), f2(num(o, "overall", "max_ms")), f0(errs), hit, lead)
	}

	pre, _ := filepath.Glob(filepath.Join(dir, "pre-coalescing", "serve-bounded-*.json"))
	sort.Strings(pre)
	if len(pre) > 0 {
		w("\n### Cache stampede: before and after request coalescing\n\n")
		w("The first measured run showed the cached mode with a *worse* tail than linearizable reads: every hot key expired on the same 2 s TTL and workers invalidated zones in bursts, so concurrent misses hit the leader together. The fix was request coalescing for misses (one store read per missed zone set, shared by concurrent requests) and TTL jitter. Same rates, same deadline, same open-loop generator:\n\n")
		w("| Entities/request | Rate (req/s) | Before: p99 / p99.9 / deadline misses | After: p99 / p99.9 / deadline misses |\n|---|---|---|---|\n")
		for _, f := range pre {
			b := load(f)
			a := load(filepath.Join(dir, filepath.Base(f)))
			if b == nil || a == nil {
				continue
			}
			miss := func(o obj) float64 { return num(o, "codes", "DeadlineExceeded") }
			w("| %s | %s | %s ms / %s ms / %s | %s ms / %s ms / %s |\n", f0(num(b, "batch")), thousands(num(b, "rate_rps")),
				f2(num(b, "overall", "p99_ms")), f2(num(b, "overall", "p999_ms")), f0(miss(b)),
				f2(num(a, "overall", "p99_ms")), f2(num(a, "overall", "p999_ms")), f0(miss(a)))
		}
	}

	w("\n## 4. Raft write path and what replication costs\n\n")
	w("Register writes through Raft from 32 closed-loop clients (each waits for its previous operation, so this measures capacity, not tail latency under a fixed rate). Every write is fsynced on a majority before it is acknowledged.\n\n")
	w("| Store | Writes/s | Write p50 / p99 (ms) | Linearizable reads/s | Read p50 / p99 (ms) | Open-loop linearizable GetFeatures at 1,000 req/s: p50 / p99 (ms) |\n|---|---|---|---|---|---|\n")
	for _, n := range []string{"1node", "5node"} {
		o := load(filepath.Join(dir, "raft-writes-"+n, "result.json"))
		lg := load(filepath.Join(dir, "serve-linearizable-b1-1000.json"))
		if n == "1node" {
			lg = load(filepath.Join(dir, "serve-linearizable-b1-1000-1node.json"))
		}
		if o == nil {
			continue
		}
		label := map[string]string{"1node": "1 node (no replication)", "5node": "5-node Raft"}[n]
		w("| %s | %s | %s / %s | %s | %s / %s | %s / %s |\n", label, thousands(num(o, "puts_per_sec")), f2(num(o, "put_p50_ms")), f2(num(o, "put_p99_ms")),
			thousands(num(o, "gets_per_sec")), f2(num(o, "get_p50_ms")), f2(num(o, "get_p99_ms")), f2(num(lg, "overall", "p50_ms")), f2(num(lg, "overall", "p99_ms")))
	}

	w("\n## 5. Write unavailability after a leader crash\n\n")
	w("`docker kill` (SIGKILL) of the leader under load, five separate runs. Unavailability = the longest stretch with no successful client write overlapping the 20 s after the kill. Election timeout is 300-600 ms (randomized); PreVote and the leader lease add a round trip.\n\n")
	files, _ = filepath.Glob(filepath.Join(dir, "leader-crash-repeats", "run-*.json"))
	sort.Strings(files)
	var vals []float64
	for _, f := range files {
		bs, _ := os.ReadFile(f)
		var arr []map[string]any
		if json.Unmarshal(bs, &arr) == nil && len(arr) > 0 {
			v, _ := arr[0]["write_unavailable_ms"].(float64)
			vals = append(vals, v)
		}
	}
	if len(vals) > 0 {
		var parts []string
		for _, v := range vals {
			parts = append(parts, f0(v))
		}
		s := append([]float64(nil), vals...)
		sort.Float64s(s)
		w("Runs (ms): %s. Median **%s ms**, min %s ms, max %s ms.\n", strings.Join(parts, ", "), f0(s[len(s)/2]), f0(s[0]), f0(s[len(s)-1]))
	}
	w("\nLinearizability, partitions and the other fault scenarios: see [`../faults/SUMMARY.md`](../faults/SUMMARY.md).\n")
	return os.WriteFile(filepath.Join(dir, "REPORT.md"), []byte(b.String()), 0o644)
}
